### ISSUE TITLE
monster direction change

### ISSUE THREAD

**Issue by emil92b** [TwistedScorpio/Nostalrius#1]
ok first off, i won't make an image for the current behaviour tonight, maby tomorrow if you don't understand what i mean.

the expected bahavior is that the monster should change it's direction according to where the player stands, i draw an image here while tested on the realots experimental server.

https://i.imgur.com/1wTviU7.png

so as you can see the monster is standing on the red square in middle, and the squares next to it is the direction it should face while player stand on that square

and if the player is standing on the same square as the monster it should be facing east

hopefully it makes sense!

**Comment by TwistedScorpio** [comment]
Hello, did you tested it in game? I'm far as I'm aware this should be reproduced as expected, hence why creatures can be cornered (e.g; Amazon, Warlock) unlike OpenTibia servers.

**Comment by emil92b** [comment]
the direction should update every attack the monster does it looks like
https://i.imgur.com/lyVgn18.jpg
so for example walking right from where i stand in the picture, it would change direction to south on next attack, and if go left then it would change direction to west on next attack

**Comment by emil92b** [comment]
there is still one more issue, maby not to the change but i noticed it after i applied it

so here is an example to reproduce it:

when you see the black box on minotaur, walk from start of this image to the end

https://i.imgur.com/9UZ7PqT.png

what happens is that the minotaur will change its direction to the south then to the east, it should not do that, it should change to the east directly

**Comment by TwistedScorpio** [comment]
Should be fixed as of (TFS #2520) https://github.com/TwistedScorpio/Nostalrius/commit/d1224058dd107f042e1fd1171a0b1abe0d4f1ee9
