### ISSUE TITLE
Hole item

### ISSUE THREAD

**Issue by rudger** [TwistedScorpio/Nostalrius#10]
If you put an item on a closed hole and you walk down the hole, the item should also go down the floor with you.

**Comment by rudger** [comment]
![nost2](https://user-images.githubusercontent.com/6645247/51804572-00adaf00-2263-11e9-93bf-7b22357c6b8e.png)

**Comment by emil92b** [comment]
floorchange.lua

change
`creature:teleportTo(relPos)`
to
`doRelocate(position, relPos)`

**Comment by TwistedScorpio** [comment]
Fixed.
[https://github.com/TwistedScorpio/Nostalrius/commit/a82933a526778e9e30bec2427d2f5041e2ec8878](url)
