### ISSUE TITLE
You cant create an empty vial.

### ISSUE THREAD

**Issue by rudger** [TwistedScorpio/Nostalrius#11]
(/i 2874,0)
(/i 2874, 0)

**Comment by emil92b** [comment]
another issue with vials that contains fluid, is that you can use on any target
`19:10 rotworm: Aaaah...`

**Comment by rudger** [comment]
What about life fluid on monsters?

Anyway there shouldnt be a text with: Aaaah...

**Comment by TwistedScorpio** [comment]
Fixed, please open a new issue when there's proof on the behavior on monsters and npcs when using fluids on them.
[https://github.com/TwistedScorpio/Nostalrius/commit/f9cff8fb05b9356a668c8cd9f41093f5f4243eac](url)

**Comment by goesraphael** [comment]
Broken Link
