### ISSUE TITLE
Orc Spearman bug

### ISSUE THREAD

**Issue by AenuSS** [TwistedScorpio/Nostalrius#13]
Orc Spearman do not attack at distance. He is just running away and attack only with melee if you are next to him.

**Comment by emil92b** [comment]
they do, but its suuper rare apparently, try summon 20+ and you'll notice it

**Comment by AenuSS** [comment]
I summoned 25 and only 1 of them will do spear attack every 15~ sec (I'm pretty sure that attack was not that super rare in real tiba). Is there any way to fix it in orcspearman.xml file? I was trying to edit chance in "<attack name="physical" min="-16" max="-40" range="7" chance="15">" and still nothing.

**Comment by TwistedScorpio** [comment]
This is intentional, login on experimental realots or watch some Tibia Cams, 15 chance is rare shoot, 1 being every time.
