### ISSUE TITLE
monster sounds

### ISSUE THREAD

**Issue by emil92b** [TwistedScorpio/Nostalrius#14]
they don't do any sounds at all, so cant test if they do it on other floors either

**Comment by emil92b** [comment]
i think this is what causing it
https://github.com/TwistedScorpio/Nostalrius/blob/009a571331504af29eb3a0296ef8c6aa336da491/src/monster.cpp#L1030

i wasn't able to fix it myself, but maby someone else can give it a try

**Comment by CristoferMartins** [comment]
@emil92b the fix can be simple change that line to:  `if (randomResult  == 50 * (randomResult / 50)) {`

**Comment by emil92b** [comment]
idk, i get debug after that change, all i did was have a demon summon next to some dwarf soldiers/guards

**Comment by TwistedScorpio** [comment]
The issue has been fixed.
[https://github.com/TwistedScorpio/Nostalrius/commit/1aaa6288a8b3ba7185271ea90580ad9b9b4d2688](url)

**Comment by BiffrosT** [comment]
Broken link for solution fixed. Please helpe?

**Comment by goesraphael** [comment]
Broken Link
