### ISSUE TITLE
issue player rooked and yours first items

### ISSUE THREAD

**Issue by renanluis90** [TwistedScorpio/Nostalrius#17]
when the player is rooked and back to rookgaard, does not return with first items again.

maybe something wrong in sources because i saw the firstItems.lua everything seems correct...

very weird because saw this code part on player.cpp
`					// Restart first items
					lastLoginSaved = 0;
					lastLogout = 0;`

**Comment by TwistedScorpio** [comment]
Fixed https://github.com/TwistedScorpio/Nostalrius/commit/10bc93365988f52c6305941a0327aaadb0b3019d
