### ISSUE TITLE
linux file system

### ISSUE THREAD

**Issue by emil92b** [TwistedScorpio/Nostalrius#19]
apparently everything works smooth on windows, but when it comes to linux, the filesystem reads the npc files, items.srv etc in reversed order, so there will be issues when talking to npc or trying to create items, maby more files will get affected idk.

**Comment by TwistedScorpio** [comment]
My server has been running on Linux for over 1 year and we have never had this issue. Filesystem is only used in the server to load the files from the folder, it does not affect the loading of the NPC's content.

**Comment by emil92b** [comment]
which linux are you using?

**Comment by TwistedScorpio** [comment]
We've been using Debian and Ubuntu, and like I've said, filesystem is only used to load NPC filenames, the filesystem is not used on the interpreter or the script system.

**Comment by emil92b** [comment]
which one so i know which one i should reinstall to? i used Debian 8 (Jessie)

**Comment by angeliker** [comment]
True i use ubuntu 14 and it doesnt work atleast the create items or summon commands dont work but it does work in windows

**Comment by TwistedScorpio** [comment]
> True i use ubuntu 14 and it doesnt work atleast the create items or summon commands dont work but it does work in windows

The system that loads script files (LUA) has nothing to do with boost::filesystem, this system is only used to obtain the filenames of the NPCs inside the npc folder, your issue is related to something else.
