### ISSUE TITLE
monster move attack delay

### ISSUE THREAD

**Issue by emil92b** [TwistedScorpio/Nostalrius#20]
it attacks normaly every 2seconds as it should, but when it moves there is 3 seconds instead, should not happen

**Comment by TwistedScorpio** [comment]
Do you have a video proof of this issue happening? I've based the code on TMonster::IdleStimulus, so further information can help fix this issue the right way, since OTS have a bug with the extra attack as far as I'm aware.

**Comment by emil92b** [comment]
just use a phone and lap each attack and you will notice it yourself, every attack when it does not move will be 2 seconds, and when it moves it delays it to 3 seconds

**Comment by renanluis90** [comment]
@emil92b i saw this issue too... i'll upload a video showing this behavior

https://streamable.com/nmps4

**Comment by emil92b** [comment]
also on realots it feels like it hits you before it even attempts to move

**Comment by TwistedScorpio** [comment]
No, I'm asking about a video of RealOTS itself.

**Comment by renanluis90** [comment]
RealOTS video
https://streamable.com/spkm6
