### ISSUE TITLE
All items in house gone.

### ISSUE THREAD

**Issue by AenuSS** [TwistedScorpio/Nostalrius#23]
After server restart all items in house are gone.

**Comment by emil92b** [comment]
do you mean after server save? or did you just close it?

/closeserver shutdown saves them for me atleast, dno about SS yet.

**Comment by AenuSS** [comment]
I was just closing server without "/close server shutdown" command. With this command items in house are saved. Thanks

**Comment by TwistedScorpio** [comment]
I'm closing this issue as it is invalid, to close the server and save at the same time, use the globalevent that comes with the server, also to close the server must always use the **"/closeserver shutdown"** command if you want to force a shutdown and save at the same time.
