### ISSUE TITLE
Lots of diconnects with OTClient

### ISSUE THREAD

**Issue by GiowGiow** [TwistedScorpio/Nostalrius#24]
Getting lots of diconnects from OTClient, compiled on Ubuntu, using OTClient with 7.72 files from official client. I get the following error:
```

Error:
ERROR: got an invalid ping from server
```

And then I'm disconnected from the server.
I don't get those disconnect or ping errors with OTHire and OTX compilled from source.

**Comment by TwistedScorpio** [comment]
You need to enable ping system in otclient.
