### ISSUE TITLE
Level 13 lag/teleport

### ISSUE THREAD

**Issue by AenuSS** [TwistedScorpio/Nostalrius#25]
When you moving on level 13 character is getting lag/teleporting back every 5-15~ seconds.
This happens on 13 lvl (maybe on some other lvls also i'm not 100% sure). It looks like problem happens only on dirt. Walking on grass/cobbled floor in city seems fine.

It must be something with movement speed because there is no such problem when I equip boots of haste or have different lvl.

Bad fps in video but you can still see teleports: https://streamable.com/papu4

**Comment by Stoudemire** [comment]
I can't reproduce this, I have already tested and it works well for me, 0 problems

**Comment by TwistedScorpio** [comment]
Didn't reproduce, issue is on your computer side.
