### ISSUE TITLE
About update soft boots

### ISSUE THREAD

**Issue by tarantonio** [TwistedScorpio/Nostalrius#26]
Now the soft boots are substracting minutes once you got them in the inventory or equiped.
At least it needs two items for the worn/unworn states. or delete the conditions and leave it only for aestethic purposes.

**Comment by TwistedScorpio** [comment]
There are no soft boots in Tibia 7.72, the item definition there is just plain decoration, the conditions are being left for those that are smart enough to implement the no decaying item state and that's it.
