### ISSUE TITLE
bug - /reload items | conjuring

### ISSUE THREAD

**Issue by emil92b** [TwistedScorpio/Nostalrius#28]
if you do a reload on items the spell name on runes doesn't show. also runes that you conjure after the reload will be unlimited charges on, but the name will be wrong regardless if you conjure before or after.

**Comment by Wirless** [comment]
its same for all distros you can only restart engine to fully reload items because of course of how map is generrated and it would mean it has to Rescan whole map taking large amount of time per item to reload them all. We need new command /update item ID
