### ISSUE TITLE
Can only target monsters inside a Rope Spot with control + click

### ISSUE THREAD

**Issue by GiowGiow** [TwistedScorpio/Nostalrius#29]
When there is a Rope Spot, targetting a monster becomes impossible with the mouse, but control + click on monster and attack works.

### Steps to reproduce

 1. Summon any monster near a rope spot
 2. When they enter a rope spot they will become untargettable 
 3. Control + click on them and you can attack them

**Comment by emil92b** [comment]
thats intended, not a bug.
