### ISSUE TITLE
using spells without double quotes

### ISSUE THREAD

**Issue by emil92b** [TwistedScorpio/Nostalrius#3]
using those 3 spells without double quotes doesn't work

exiva name
exani hur down/up
exura sio name

**Comment by Felipe21** [comment]
you can edit it at spells.cpp
 compare ond sources with these and make the editions 
good luck :) cipsoftstinks here

**Comment by emil92b** [comment]
https://i.imgur.com/s3FKjWw.png
confirmed

**Comment by emil92b** [comment]
it can be fixed by removing on this line https://github.com/TwistedScorpio/Nostalrius/blob/master/src/spells.cpp#L215
` || words[spellLen + 1] != '"'`

**Comment by emil92b** [comment]
need to research if it should be possible to exiva names with 2 or more words in it, example: 
"exiva kalle anka"
