### ISSUE TITLE
BLOCK SOLID AVOIDING USE RUNES

### ISSUE THREAD

**Issue by caioabranches2009** [TwistedScorpio/Nostalrius#30]
Hello, when you go upstairs on ladder, and there's a small table (unpass item) down you, you cannot use runes on your self or be targeted from runes of other players.

**Comment by emil92b** [comment]
confirmed it's bugged, returns 'there is not enough room'

works on realots: https://i.imgur.com/qAmhppD.png

**Comment by TwistedScorpio** [comment]
Fixed https://github.com/TwistedScorpio/Nostalrius/commit/b7a150f324d1c00b75e5a7d532d3ca7ab672cb2e
