### ISSUE TITLE
losing promotion

### ISSUE THREAD

**Issue by caioabranches2009** [TwistedScorpio/Nostalrius#31]
when u lose premium account, you lose promotion, but if you buy premium again, you'll be promoted again, but it's not happening, when player buy premium for the second time

**Comment by tarantonio** [comment]
login.lua
`if player:isPremium() then
        if player:getVocation():getId() ~= 0 and player:getVocation():getId() < 5 and player:getStorageValue(30018) == 1 then
            player:setVocation(player:getVocation():getId() + 4)
        end
    else
        if player:getVocation():getId() ~= 0 and player:getVocation():getId() > 4 then
            player:setVocation(player:getVocation():getId() - 4)
            player:setStorageValue(30018, 1)
        end
    end`

**Comment by babymannen** [comment]
It will work if you add storage: 30018, 1 when promoting a player.

**Comment by TwistedScorpio** [comment]
> It will work if you add storage: 30018, 1 when promoting a player.

Behaviordatabase is already adding storage 30018 when promoting the player, the issue is maybe inside login script.

**Comment by TwistedScorpio** [comment]
Could not reproduce, Promote function always sets the storage value 30018 for the player and the login script takes care of the rest.
