### ISSUE TITLE
Cure Poison (exana pox) doesn't work while moving

### ISSUE THREAD

**Issue by tysonstrange** [TwistedScorpio/Nostalrius#32]
Seems casting exana pox while walking/running doesn't cure poison, but seems to work if you're standing still.

**Comment by renanluis90** [comment]
yes! i saw this bug

**Comment by renanluis90** [comment]
Hello, 

Someone can test? 

In Player.cpp

Change 

void Player::onWalk(Direction& dir)
{
	Creature::onWalk(dir);
	setNextActionTask(nullptr);
	setNextAction(OTSYS_TIME() + getStepDuration(dir));
}

To 

void Player::onWalk(Direction& dir)
{
	Creature::onWalk(dir);
	setNextActionTask(nullptr);
	//setNextAction(OTSYS_TIME() + getStepDuration(dir));
}

I really do not know if it can affect other things, someone give me the feedback please.
