### ISSUE TITLE
weird warlocks invisible chance

### ISSUE THREAD

**Issue by renanluis90** [TwistedScorpio/Nostalrius#33]
comparing monsters chances:
Stalkers.xml
<defense name="invisible" duration="30000" chance="4">
Warlocks.xml
<defense name="invisible" duration="20000" chance="10">

and I also see that the stalkers do not return to normal

my record video 5 minutes i think is a good time to test with much wl's
https://streamable.com/i9tsd

**Comment by babymannen** [comment]
Not sure why the Warlocks doesn't want to go invisible. However, the reason why stalkers will never return to normal I pointed out in an issue at the TheForgottenServer repository, but never got fixed:

https://github.com/otland/forgottenserver/issues/2410

**Comment by renanluis90** [comment]
Idk too, because if we check chance of stalker and warlock, stalkers have less chances to invisible, very weird this

**Comment by TwistedScorpio** [comment]
> Idk too, because if we check chance of stalker and warlock, stalkers have less chances to invisible, very weird this

The chances are the opposite way on CipSoft, Warlocks are actually rarer to become invisible than a Stalker, however, this one particular problem is part of TFS itself that has to be addressed.

**Comment by tarantonio** [comment]
There is a pull request from Nekiro to fix this issue:
[https://github.com/otland/forgottenserver/pull/2545](url)
