### ISSUE TITLE
some issues after latest fixes

### ISSUE THREAD

**Issue by emil92b** [TwistedScorpio/Nostalrius#39]
* player/monster summons don't move (https://github.com/TwistedScorpio/Nostalrius/commit/87ba59c649bf38507898a39253b3b7469396474f) - **fixed**

* spell visual wrong order? https://imgur.com/a/CC4SvnQ
* cannot use runes on fields it returns 'there is not enough room'
* monster direction change - posted comment here https://github.com/TwistedScorpio/Nostalrius/commit/d1224058dd107f042e1fd1171a0b1abe0d4f1ee9#commitcomment-33169361
* your summon doesn't follow you when you have attack on it (it should follow)
* changing floors after /ghost has been activated, removes the invisible state

**Comment by tarantonio** [comment]
There is no cooldown on monster spells, they are now spamming spells all the time.

**Comment by tarantonio** [comment]
![firebomb2](https://user-images.githubusercontent.com/7066891/57314362-ca00f380-70f1-11e9-8187-4baed859761a.gif)
3rd issue fixed on pull request

**Comment by waqmaz93** [comment]
> ![firebomb2](https://user-images.githubusercontent.com/7066891/57314362-ca00f380-70f1-11e9-8187-4baed859761a.gif) 3rd issue fixed on pull request

the fire field shoulnd not be teleported downstairs and using fire ball should be visible on the stairs

**Comment by goesraphael** [comment]
Any update for itens 2, 5 and 6?
