### ISSUE TITLE
NPC: blocked container (BP)

### ISSUE THREAD

**Issue by niubi-otland** [TwistedScorpio/Nostalrius#4]
Example:
I have bag in inventory. 7 items + 1 backpack in that bag.

When I'm trying to buy 2 items from npc, it goes on the ground instead of that 1 bp in my bag.

**Comment by TwistedScorpio** [comment]
Hello, as far as I can recall, this was intentional as this was the behavior on RealOTS files back in the day, it still happens on modern Tibia with certain chests too.

**Comment by niubi-otland** [comment]
But don't you think it shouldn't work like that?

**Comment by TwistedScorpio** [comment]
If you would like it to work like every other OT, un-comment the lines inside player.cpp (queryDestination) function.

**Comment by TwistedScorpio** [comment]
You may now re-enable this feature, please be careful with CPU usage on servers with many many items and no capacity limit wise.

[https://github.com/TwistedScorpio/Nostalrius/commit/6e02936226f6251089d01b5a70d144ac5dce2594](url)
