### ISSUE TITLE
(bug) conjure rune slots

### ISSUE THREAD

**Issue by emil92b** [TwistedScorpio/Nostalrius#5]
current
* rune in right hand = right slot gets conjured (working)
* rune in left hand = left slot does not get conjured and return message 'You need a magic item to cast this spell.' (problem)
* rune in both hands, right slot gets conjured, left slot does not get conjured (problem)

expected
* should be possible to conjure in either hands and both of them

confirmed
https://i.imgur.com/EDiG3a8.jpg

**Comment by renanluis90** [comment]
Are u testing things only with GOD or Gamemaster? If yes, test with normal characters too...

**Comment by emil92b** [comment]
you're right, my bad. never thought it would act like that on a gamemaster
