### ISSUE TITLE
throw distance

### ISSUE THREAD

**Issue by emil92b** [TwistedScorpio/Nostalrius#55]
was a long time since i played around with these ot files, but i just discovered that the throwing distance doesn't seem to be that accurate, here is a comparison:

![123](https://user-images.githubusercontent.com/43324808/70586344-13a14780-1bc7-11ea-99a0-232bce7ef591.PNG)

is any1 still working with these files fixing stuff? : )

**Comment by AK94PL** [comment]
Anyone know how to fix this?

**Comment by goesraphael** [comment]
Where is the fix?
