### ISSUE TITLE
If your first backpack is full, items will fall on the ground even if you have an empty backpack in your full backpack

### ISSUE THREAD

**Issue by ostur** [TwistedScorpio/Nostalrius#63]
Even if you have an empty backpack within your full backpack, items that you buy, quest rewards, everything will fall on the ground

![e6ed07e0e5f90b87e153d5488da075ab](https://user-images.githubusercontent.com/21351470/99894518-cce81880-2c84-11eb-92aa-a6778a274f5e.png)

**Comment by tysonstrange** [comment]
Have not found this to be the case

**Comment by ostur** [comment]
I'm sorry, seems like you can change this in config, see _queryPlayerContainers.

**Comment by RCP91** [comment]
i have also problem, this  _queryPlayerContainers. its dont work to me.
