### ISSUE TITLE
field mechanics

### ISSUE THREAD

**Issue by emil92b** [TwistedScorpio/Nostalrius#7]
# ENERGY FIELD (tick/refresh every 11 seconds)
tested on 80ms, ml 45

if a player cast a field it will do -50% damage (rounded up), if wait 5 seconds it should do normal damage.

**step into (normal damage)**

	23:47 You lose 30 hitpoints. (tick) (x1)
	23:47 You lose 25 hitpoints. (tick) (x1)

**step into (player damage)**

	00:08 You lose 15 hitpoints due to an attack by Janaja. (tick) (x1)
	00:09 You lose 13 hitpoints due to an attack by Janaja. (tick) (x1)

**cast on self/target (player damage)**

	23:29 You lose 15 hitpoints due to an attack by Janaja. (tick) (x1)
	23:29 You lose 13 hitpoints due to an attack by Janaja. (tick) (x1)

**stand still on field (until it expires)**

	(normal damage) - need testing

	(player damage) - need testing

# FIRE FIELD (tick/refresh every 9 seconds)
tested on 80ms, ml 45

if a player cast a field it will do -50% damage (rounded up), if wait 5 seconds it should do normal damage.

**step into (normal damage)**

	00:14 You lose 20 hitpoints. (tick) (x1)
	00:14 You lose 10 hitpoints. (tick) (x7)

**step into (player damage)**

	00:40 You lose 10 hitpoints due to an attack by Janaja. (tick) (x1)
	00:40 You lose 5 hitpoints due to an attack by Janaja. (tick) (x7)

**cast on self/target (player damage)**

	00:50 You lose 10 hitpoints due to an attack by Janaja. (tick) (x1)
	00:50 You lose 5 hitpoints due to an attack by Janaja. (tick) (x7)

**stand still on field (until it expires)**

	(normal damage) - need testing

	(player damage) - need testing

# POISON FIELD (tick/refresh every 4 seconds)
tested on 80ms, ml 45

if a player cast a field it will do -50% damage (rounded up), if wait 5 seconds it should do normal damage.

**step into (normal damage)**

	00:17 You lose 5 hitpoints. (tick) (x1)
	00:17 You lose 4 hitpoints. (tick) (x4)
	00:17 You lose 3 hitpoints. (tick) (x7)
	00:18 You lose 2 hitpoints. (tick) (x10)
	00:18 You lose 1 hitpoint. (tick) (x38)
	total 100 damage.

**step into (player damage)**

	00:25 You lose 3 hitpoints due to an attack by Janaja. (tick) (x1)
	00:25 You lose 2 hitpoints due to an attack by Janaja. (tick) (x11)
	00:25 You lose 1 hitpoint due to an attack by Janaja. (tick) (x48)
	total 73 damage.

**cast on self/target (player damage)**

	01:27 You lose 3 hitpoints due to an attack by Janaja. (tick) (x1)
	01:27 You lose 2 hitpoints due to an attack by Janaja. (tick) (x11)
	01:28 You lose 1 hitpoint due to an attack by Janaja. (tick) (x48)
	total 73 damage.

**stand still on field (until it expires)**

**(normal damage)**

        01:18 You lose 5 hitpoints. (tick) (x1)
        01:18 You lose 4 hitpoints. (tick) (x6)
        01:18 You lose 3 hitpoints. (tick) (x10)
        01:19 You lose 2 hitpoints. (tick) (x19)
        01:20 You lose 1 hitpoint. (tick) (x63)
        total 160 damage.

**(player damage)**

        01:33 You lose 3 hitpoints due to an attack by Janaja. (tick) (x1)
        01:33 You lose 2 hitpoints due to an attack by Janaja. (tick) (x16)
        01:34 You lose 1 hitpoint due to an attack by Janaja. (tick) (x84)
        total 119 damage.

**Comment by Wirless** [comment]
i fixed it on my tfs 0.4 look for damage / 2 and then just delete / 2 I cant find the right line for it but after that it will work

**Comment by TwistedScorpio** [comment]
I need more information concerning this issue.

**Comment by emil92b** [comment]
updated the issue, there you go @TwistedScorpio
