### ISSUE TITLE
undead legion spell

### ISSUE THREAD

**Issue by emil92b** [TwistedScorpio/Nostalrius#8]
currently it doesn't work, only return not possible and poff effect

this is how it should be
rat: https://gyazo.com/ef1fce0c67468f9739cb94d01826f786
nothing: https://gyazo.com/380a033879d72fb2c8d948421ae7b8cb

**Comment by TwistedScorpio** [comment]
Could not reproduce this issue, not able to cast the spell if there are no corpses around the player, closing it as it is invalid.
