### ISSUE TITLE
area spells should not be random

### ISSUE THREAD

**Issue by emil92b** [TwistedScorpio/Nostalrius#9]
so i tested what @Peonso had to say, and it seems to be true that the damage is being calculated for each target it hits

this repository
https://i.imgur.com/FkXLI0O.png

how it should work
https://i.imgur.com/5OrZkzK.png

also here is a great energy beam from 7.4 : p
https://i.imgur.com/y94eEMt.png

**Comment by goesraphael** [comment]
Why closed? Where is the fix?
